// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi66fgpyDMaw_WFfw996mu2xBEFfYIuWo',
    appId: '1:449272350231:web:55410f31799f0487c8fe52',
    messagingSenderId: '449272350231',
    projectId: 'flutter-group-chat-cfeab',
    authDomain: 'flutter-group-chat-cfeab.firebaseapp.com',
    storageBucket: 'flutter-group-chat-cfeab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqk-vFrNarxkR3vMKhtRs8K1GXR5-_tow',
    appId: '1:449272350231:android:6ad82d6e06cacd0ac8fe52',
    messagingSenderId: '449272350231',
    projectId: 'flutter-group-chat-cfeab',
    storageBucket: 'flutter-group-chat-cfeab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO9M_7HJRjEcEnEL9UwVyDuTcHbSSZIpk',
    appId: '1:449272350231:ios:864b52fc6a002649c8fe52',
    messagingSenderId: '449272350231',
    projectId: 'flutter-group-chat-cfeab',
    storageBucket: 'flutter-group-chat-cfeab.appspot.com',
    iosBundleId: 'com.example.groupChatApp',
  );
}
